### ISSUE TITLE
你好，看到你写的这个列表，结构感觉非常好，但是怎么做解析？

### ISSUE THREAD

**Issue by LGLee** [zhujia18/JPDiscover#5]
看到你写的这个列表，结构感觉非常好，但是怎么做解析。当我们把数据拉下来的时候，多为列表状态，使用第三方框架如:mjextension等解析放入一个模型数组中，如果这样的话我是不是需要耗时去再对这个模型数组中的模型再做一次解析，以解析出对应titleModel，ContentModel等？？

**Comment by zhujia18** [comment]
抱歉回复晚了，这里面为了解耦合加入了一个数据中间层model，每个tab下的VC都是独立的，在每个VC里面获取到你的model或者是直接用dic转换成中间层model即可~当然也可以直接改写在不同模块里面的model换成你自己的~

**Comment by LGLee** [comment]
也就是我要对每一次的拉下来的列表数据进行一次遍历，然后拆分成一个个子模块数据（如：titleModule，imageModule数据等），然后将数据分发到不同的模块吗
